services:
  - type: web
    name: aero-track-4d
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python -m uvicorn src.api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
